# -*- coding: utf-8 -*-
"""projeto calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5s1dcVXJg3CPBFYUvuEcmYYQ_vFHKiP
"""

nome = input('Digite seu nome:')
print('Olá,', nome, 'vamos começar!')


num1 = input ('digite um número:')
num1conver = float(num1)

num2 = input ('digite um número:')
num2conver = float(num2)

print('Escolha a operação:')
print('1 - soma')
print('2 - subtração')
print('3 - multiplicação')
print('4 - divisão')

operacao = input('Digite o úmero da operação desejada:')

if operacao == '1':
  resultado = num1conver + num2conver
  print(f'o resultado da soma é:{resultado}')
elif operacao == '2':
  resultado = num1conver - num2conver
  print(f'o resultado da subtração é:{resultado}')
elif operacao == '3':
  resultado = num1conver * num2conver
  print(f'o resultado da multiplicação é:{resultado}')
elif operacao == '4':
  resultado = num1conver / num2conver
  print(f'o resultado da divisão é:{resultado}')